# Image
FROM node:18-alpine

# Set up the working directory
WORKDIR /var/www/html

# Specify the host variable
ENV HOST 0.0.0.0

# Expose the Nuxt port
EXPOSE 3000

# Run the Nuxt service
CMD ["yarn", "dev"]
