version: '3.8'

services:
  app:
    build:
      dockerfile: .docker/dev/app/Dockerfile
    volumes:
      - ./:/var/www/html
    hostname: client
    ports:
      - "3000:3000" # The Nuxt app port
    networks:
      - client
      - gateway
    restart: unless-stopped

networks:
  client:
    name: client

  gateway:
    name: gateway
    external: true
